### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Noumamayo** [Alecaddd/Sunset-theme#7]
i will try many time to download these files but i am  not able to do this after 12 % download stop and show error please resolve this issue ,,

**Comment by Noumamayo** [comment]
please send me at may mail 
noumanmayo007@gmail.com

**Comment by Alecaddd** [comment]
I'm sorry for your issues but it doesn't depend on me.
It's probably GitHub or your Internet provider.
All my source code is up here so I don't have to send private emails with MBs of data.
